version: '2'
services:
    web:
        container_name: cage_web_1
        build: docker/nginx
        working_dir: /app
        environment:
            - VIRTUAL_HOST=cage.docker
            - VIRTUAL_PORT=80
        links:
            - php
        volumes_from:
            - app
        depends_on:
            - php

    app:
        container_name: cage_app_1
        image: busybox:latest
        working_dir: /app
        volumes:
            - .:/app

    php:
        container_name: cage_php_1
        build: docker/php-fpm
        working_dir: /app
        volumes_from:
            - app
