version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Update packages
          command: apt-get update
      - run:
          name: Install basic Unix tools
          command: apt-get install bzip2 -y
      - run:
          name: Install necessary tools
          command: apt-get install git zip unzip -y
      - run:
          name: Install Composer
          command: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - run:
          name: Install PHP dependencies
          command: make install
      - run:
          name: Run php webserver
          command: php -S localhost:8888 -t ./public
          background: true
      - run:
          name: Run tests
          command: make test
