version: 2
jobs:
   build:
     working_directory: ~/cage-api
     docker:
       - image: circleci/php:7.0
     steps:
       - checkout
       - setup_remote_docker
       - run: pwd
       - run: ls -lah
       - run: curl -sSL https://s3.amazonaws.com/circle-downloads/install-circleci-docker.sh | bash -s -- 1.10.0
       - run: pip install --upgrade pip
       - run: pip install docker-compose
       - run: make build:dev
       - run: make install
       - run: make test
       - deploy:
           name: Maybe Deploy
           command: |
             if [ "${CIRCLE_BRANCH}" == "master" ]; then
               bash ./.circleci/deploy-dokku.sh
             fi
