version: 2
jobs:
   build:
     working_directory: ~/cage-api
     docker:
       - image: circleci/php:7.0
     steps:
       - checkout
       - setup_remote_docker
       - run:
           name: Install Docker Compose
           command: |
             set -x
             curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
             chmod +x /usr/local/bin/docker-compose
       - run: make build:dev
       - run: make install
       - run: make test
